const poi = [
    {
        "html":"<h1 class='text-2xl font-bold'>Mendez v. Westminster</h1> <p>Mendez v. Westminster was a landmark civil rights court case for Latinx people. It was an important precedent for Brown v. BoE, and helped to pave the way for the civil rights movement. The Mendez children, who had previously had no problem attending white schools, had moved to the Westminster school district in 1945. They were rejected from Westminster Elementary school because of their 'Mexican appearance'. The Treaty of Guadalupe Hidalgo officially classified Mexican-Americans as White on the census, however many school districts began creating separated Mexican and White schools in the 1930's. The superintendent of one such district even went so far as to say that 'People of Mexican descent were intellectually, culturally, and morally inferior to European Americans.' The Mendez family sued the Westminster School District, and Judge Paul McCormick ruled that the district's segregation of Mexican and White students was unconstitutional. <img class='image' src='https://s3.amazonaws.com/s3.timetoast.com/public/uploads/photos/12204022/220px-MendezVWestImage.jpg'alt='Mr. and Mrs. Mendez'><p class='subtext'>Mr and Mrs Mendez.</p></p>"
    },
    {
        "html":"<h1 class='text-2xl font-bold'>El Primer Congreso Mexicanista</h1> <p>After years of oppression and even lynchings in Texas, a group called El Primer Congreso Mexicanista (The first Mexicanist Congress) formed in Laredo, Texas. The goal of the group was to express disdain for the intense civil rights violations against Mexicans by Anglo-Texans, notably the lynchings, segregation, and labor exploitation. The conventions were publicized by Laredo's Spanish-language newspaper (La Cronica), and hundreds of community members, activists, and journalists attended. The group managed to bring unprecedented levels of attention to Mexican civil rights in Texas. <img class='image'src='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.8vMrWQi5Fw4HyXonlXt9JQHaFg%26pid%3DApi&f=1&ipt=cb369548ea4f8fa9bd87e0712c73386c9433f83c5e860a850e87b52df2edc689&ipo=images' alt='photo of el primer congreso mexicanista attendees'><p class='subtext'>Photo of some attendees.</p></p>"
    },
    {
        "html": "<h1 class='text-2xl font-bold'>Pecan Shellers Strike</h1><p>In San Antonio, Texas, in 1938, thousands of Hispanic pecan shellers (mostly women), organized and marched out of their workplaces to protest the unfair pay and horrible working conditions. Lasting for 3 months, the Pecan Shellers Strike brought attention to the plight of the workers, and caused confrontations between the workers, the pecan companies, and even local government. Pecan shelling was incredibly important in this area, with San Antonio hosting around 50% of the US pecan industry. Additionally, Mexican Americans made up around 40% of the local population. Thousands of people worked as pecan shellers, earning $3 a week for 10 hour workdays every day. Due to the large amounts of fine dust presented by the pecans, many even got Tuberculosis. The Southern Pecan Shelling company (among others) even lowered wages, sparking the peaceful strike. Protesters were met by the police who were supported by the local government, and hundreds were arrested and sent into overcrowded cells. Eventually, the Texas Industrial Commission stated that the police response was excessive and ruled in favor of the strikers and foced the shelling companies to raise wages.<img class='image' src='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.JNeDb79WUWwAFQtrIidKpgHaE0%26pid%3DApi&f=1&ipt=ff4fd4301c358033f4a3cbace1fe04d8550117137829b5650e03a0782e02d622&ipo=images'alt='Photo of pecan shellers'><p class='subtext'>Workers in a pecan-shelling plant.</p></p>"
    },
    {
        "html": "<h1 class='text-2xl font-bold'>East Los Angeles Walkouts</h1> <p>In March of 1968, thousands of Mexican American students in the East Los Angeles area walked out of their classes to protest inequalities in the school system. At the time, many Mexican American schools were run down and crowded, and mainly taught career skills and not the academic skills required for colleges, funneling most students towards a life of labor. Social Studies teacher Sal Castro began teaching academic skills to his students, and ended up as one of the leaders of the walkouts. In total, the walkouts involved around 20,000 students. They were originally met with police intimidation, though the protests eventually prompted negotiatons with the school board and caused some reforms, though the 13 major leaders (known as the East LA 13) were arrested. <img class='image' src='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.Mur8h8FF8bRRj61NqYlzcAHaE8%26pid%3DApi&f=1&ipt=acc948dec9781bf4391ecd4af6960e94ec255ad218f6a9968ead156113b3592f&ipo=images'alt='photo of sal castro'><p class='subtext'>Sal Castro.</p></p>"
    },
    {
        "html": "<h1 class='text-2xl font-bold'>Miranda v. Arizona</h1> <p>The Fifth Amendment gives individuals the right to an attorney and the right to be silent. Ernesto Miranda was arrested in his house on March 13, 1963 and brought to the police station, where he was interrogated for 2 hours on suspicion of connection to a kidnapping and rape case, without ever being informed of his rights. After the 2 hours, the police obtained a written confession from Miranda, which was used as evidence in the trial despite the objections of the defense attorney. Miranda was found guilty by the jury. The Supreme Court voted 5-4 in favor of Miranda, with Chief Justice Warren's verdict stating that the interrogation of Miranda without information of rights violated the 5th Amendment and was therefore unconstitutional. Because of this case the Miranda Rights that are now required by law were created, making it an important landmark in history, both Latinx and general.<img class='image' src='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.nVxUy72uV-IQIqLkwShLnwHaFj%26pid%3DApi&f=1&ipt=1ddaa1e84a04ead4a3adb4a22b06a29b65d0241fad8315369ea56b78f54e6c3a&ipo=images'alt='Mr. Miranda's mugshot><p class='subtext'>Mr. Miranda's mugshot</p></p>"
    },
    {
        "html": "<h1 class='text-2xl font-bold'>United Farm Workers Union</h1> <p>In 1962, a union was formed in Delano, California by Cesar Chavez, Dolores Huerta, and other civil rights activists. It was called the National Farm Workers Association, and defended the rights of California's farmworkers with nonviolent tactics based on Catholic teachings. Many farm workers suffered from terrible conditions, such as pesticide exposure, poor food and shelter, and even sexual harassment, and recieved very low wages. The union sought to correct this, and managed to gain higher wage contracts and better working conditions through organized marches, boycotts, and other tactics. They were published in national headlines and gained a lot of attraction and members. <img class='image' src='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fufw.org%2Fwp-content%2Fuploads%2F2019%2F03%2Ffront4b.jpg&f=1&nofb=1&ipt=59c6794e9ff0768ca1eb2ded19c601f48c5c9f36928a6fe244b980b46b1c37bd&ipo=images'alt='UFW union marchers'><p class='subtext'>United Farm Workers Union marchers</p></p>"
    },
    {
        "html": "<h1 class='text-2xl font-bold'>Hernandez v. Texas</h1> <p>Hernandez v. Texas was a landmark Supreme Court case that happened in 1954. The unanimous ruling stated that the 14th Amendment applied to every and all racial or ethnic groups facing discrimination. Defendant Peter Hernandez was an agricultural worker in Texas, convicted of murder. His legal team, comprised primarily of members of one of the oldest Latinx civil rights groups at the time, appealed the case. Hernandez's legal team found that not one of the 6,000-odd jurors over the previous 25 years had a Hispanic last name, and claimed that Hernandez recieved an unfair trial. To back this up, they cited the 14th Amendment, which was passed in 1868 and guaranteed equal protection under the law to African Americans. Hernandez and his team used this precedent to claim that he did not recieve equal treatment, because the jury did not contain any Hispanics, and thus he was not tried by a jury of peers. When the case went to the Supreme Court, Texan lawyers claimed that Hernandez's argument was incrrect, and that the 14th Amendment applied only to African Americans. Chief Justice Earl Warren dismissed this, stating that 'The Fourteenth Amendment is not directed solely against discrimination due to a two-class theory.'<img class='image' src='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimage.pbs.org%2Fvideo-assets%2Fpbs%2Famerican-experience%2F105062%2Fimages%2FMezzanine_067.jpg&f=1&nofb=1&ipt=774627334ec465b206959e083734b0e8ba28c8356ccfd1885956ef521b212e21&ipo=images'alt='Hernandez and his legal team'><p class='subtext'>Hernandez and his legal team.</p></p>"
    }
];
